### ISSUE TITLE
Add Fields of Mistria's Wiki.gg Page

### ISSUE THREAD

**Issue by RABIDYOTE** [wiki-gg-oss/redirect-extension#83]
**Is your feature request related to a problem? Please describe.**
Fields of Mistria has its own wiki.gg page but isn't added as a redirect yet.

**Describe the solution you'd like**
For the FoM Fandom page ([fields-of-mistria.fandom.com](fields-of-mistria.fandom.com)) to redirect accordingly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Extra information** (if applicable)
- Using on Firefox
- Wiki: Fields of Mistria ([fieldsofmistria.wiki.gg](fieldsofmistria.wiki.gg))

**Comment by alex4401** [comment]
Seems to had been added on September 11th. Can you open the extension's panel and let me know what version is listed at the bottom of the panel?
