### ISSUE TITLE
Add Bloons wiki page in the redirect

### ISSUE THREAD

**Issue by cre-w** [wiki-gg-oss/redirect-extension#89]
There is a new wiki for the bloons universe, that isn't hosted on fandom
Old wiki: https://bloons.fandom.com/wiki/Bloons_Wiki
New wiki: https://www.bloonswiki.com

**Comment by MrPie5** [comment]
This extension only supports wiki.gg wikis.
For other platforms, try Indie Wiki Buddy: https://github.com/KevinPayravi/indie-wiki-buddy
